services:
  - type: web
    name: deen-gpt-backend
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn api.server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
