services:
  - type: web
    name: deen-gpt-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api.server:app
    plan: free
    autoDeploy: true
