services:
  - type: web
    name: deen-gpt-backend
    env: python
    plan: free
    buildCommand: ""
    startCommand: python api/server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
