services:
  - type: web
    name: deen-gpt
    env: python
    buildCommand: |
      pip install -r requirements.txt
startCommand: gunicorn api.server:app --bind 0.0.0.0:$PORT
    # Ensure you replace `api.server:app` with the actual path where your app instance is located
    # $PORT is automatically set by Render for port binding
    plan: free
    # Optional: Add custom environment variables if needed
    envVars:
      - key: FLASK_ENV
        value: production
