services:
  - type: web
    name: deen-gpt-backend
    runtime: python
    region: oregon  # or use frankfurt/dublin depending on your location
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app

    envVars:
      - key: PYTHON_VERSION
        value: 3.10
